settings:
  # Filepath for your PP Chatlogs
  # EXAMPLE: "C:/Users/USERNAME/Documents/YPP Chatlogs/"
  filepath: "C:/Users/Jared/Documents/YPP Chatlogs/"
  # Filename for your PP Chatlogs
  # EXAMPLE: "Jice_emerald"
  filename: "Jice_emerald_x"
  # Resize Window, if set to False it will always be the largest setting
  # Recommended setting: True
  resize_window: True
  # Display only group numbers. True = Smaller, less information dense rumble aid
  # Recommended setting: False
  display_only_group_numbers: False
  # Show rumble only after vargas. True = Rumble table only from fray 5.
  # Recommended setting: False
  show_rumble_only_after_vargas: False
  # Bars as natural width. True = Rumble chart will have width of 0 drop off punches.
  # Recommended setting: False
  bars_as_natural_width: False
  # Drop off numbers. True = Shows required drop off for max width.
  # Recommended setting: False
  drop_off_numbers: True
  # Rumble scaling. Size of the rumble chart, 4 = in game size
  # Recommended setting: 12
  rumble_scaling: 12
  # fps cap. How many times per second the program loops, setting this number high will use more resources but give a more accurate timer.
  # Recommended setting: 5 to 20
  fps_cap: 60
  # Fray countdown_on. Gives you a 17 second countdown until the start of CI frays
  # Recommended setting: True
  fray_countdown_on: True
  # Timer Decimals. How many decimals you want for the Forage/TH timer
  # Recommended setting: 0 or 1
  timer_decimals: 1
  # Rumble Warning Sound. Plays a sound 10 seconds before the minute mark in rumble incase you may want to save your punch 
  # Recommended setting: False
  rumble_warning_sound: True
  # Plank Swabbie Warning Sound. Plays a sound when you should plank the swabbies
  # Recommended setting: True
  swabbie_warning_sound: True
  # Forage/TH Timer. Plays a timer for forage in CI and TH in lairs
  # Recommended setting: True
  puzzle_timer: True